name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

env:
  SERVICE_NAME: key_management_service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.*

      - name: Build
        run:  dotnet build --configuration Release
  
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.*

      - name: Run Unit Tests
        run:  dotnet test

  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: dockerhub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker Image
        run: |
          TAG=${GITHUB_SHA}
          docker build . -t fossapps/$SERVICE_NAME --build-arg VERSION=$TAG
          docker tag fossapps/$SERVICE_NAME fossapps/$SERVICE_NAME:$TAG
          docker push fossapps/$SERVICE_NAME:$TAG

  publish:
    needs: [ build-docker-image ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: dockerhub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/git@10.0.1
            @semantic-release/exec@6.0.2
            @semantic-release/changelog@6.0.1
